"""empty message

Revision ID: f78e272c26e3
Revises: a66f0220ad9a
Create Date: 2024-09-22 16:44:25.810309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f78e272c26e3'
down_revision: Union[str, None] = 'a66f0220ad9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_student_tokens_id', table_name='student_tokens')
    op.drop_index('token', table_name='student_tokens')
    op.drop_table('student_tokens')
    op.drop_index('ix_tokens_id', table_name='tokens')
    op.drop_index('token', table_name='tokens')
    op.drop_table('tokens')
    op.drop_index('ix_students_email', table_name='students')
    op.drop_index('ix_students_student_id', table_name='students')
    op.drop_table('students')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('student_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('student_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_students_student_id', 'students', ['student_id'], unique=False)
    op.create_index('ix_students_email', 'students', ['email'], unique=True)
    op.create_table('tokens',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('token_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('expires_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('token', 'tokens', ['token'], unique=True)
    op.create_index('ix_tokens_id', 'tokens', ['id'], unique=False)
    op.create_table('student_tokens',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('token_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('expires_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('token', 'student_tokens', ['token'], unique=True)
    op.create_index('ix_student_tokens_id', 'student_tokens', ['id'], unique=False)
    # ### end Alembic commands ###
