"""empty message

Revision ID: f7f7d2104cfa
Revises: d7f0825ffe44
Create Date: 2024-09-21 15:49:12.141843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7f7d2104cfa'
down_revision: Union[str, None] = 'd7f0825ffe44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lib_admin',
    sa.Column('lib_admin_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('lib_admin_id')
    )
    op.create_index(op.f('ix_lib_admin_email'), 'lib_admin', ['email'], unique=True)
    op.create_index(op.f('ix_lib_admin_lib_admin_id'), 'lib_admin', ['lib_admin_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lib_admin_lib_admin_id'), table_name='lib_admin')
    op.drop_index(op.f('ix_lib_admin_email'), table_name='lib_admin')
    op.drop_table('lib_admin')
    # ### end Alembic commands ###
